name: Bot taches maison


on:
  schedule:
    - cron: "0 3 * * *"   # 06:00 Kampala
    - cron: "0 18 * * *"  # 21:00 Kampala
  workflow_dispatch:

jobs:
  run-bot:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - uses: actions/setup-python@v5
        with:
          python-version: "3.11"

      - run: pip install pandas requests

      # ðŸŒ… Message du matin
      - name: Morning message
        if: github.event.schedule == '0 3 * * *'
        run: python bot.py
        env:
          TOKEN_TELEGRAM: ${{ secrets.TOKEN_TELEGRAM }}
          MODE: morning

      # ðŸŒ™ Rappels du soir
      - name: Evening reminders
        if: github.event.schedule == '0 18 * * *'
        run: python bot.py
        env:
          TOKEN_TELEGRAM: ${{ secrets.TOKEN_TELEGRAM }}
          MODE: evening
