name: Bot taches maison

on:
  schedule:
    - cron: "0 4 * * *"
    - cron: "0 18 * * *"
  workflow_dispatch:

jobs:
  run-bot:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - uses: actions/setup-python@v5
        with:
          python-version: "3.11"

      - run: pip install pandas requests

      - name: Morning task message
        if: github.event.schedule == '0 4 * * *'
        run: python bot.py
        env:
          TOKEN_TELEGRAM: ${{ secrets.TOKEN_TELEGRAM }}
          MODE: morning

      - name: Cooking reminder
        if: github.event.schedule == '0 18 * * *'
        run: python bot.py
        env:
          TOKEN_TELEGRAM: ${{ secrets.TOKEN_TELEGRAM }}
          MODE: cooking

      - name: Cleaning reminder
        if: github.event.schedule == '0 18 * * *'
        run: python bot.py
        env:
          TOKEN_TELEGRAM: ${{ secrets.TOKEN_TELEGRAM }}
          MODE: cleaning
