name: Bot t√¢ches maison

on:
  schedule:
    - cron: '0 4 * * *'   # 07h Ouganda
    - cron: '0 16 * * *'  # 19h Ouganda
    - cron: '0 18 * * *'  # 21h Ouganda
  workflow_dispatch:

jobs:
  run-bot:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-python@v4
        with:
          python-version: '3.10'
      - run: pip install pandas requests

      - name: Morning messages
        if: github.event.schedule == '0 4 * * *'
        run: MODE=morning python bot.py
        env:
          TOKEN_TELEGRAM: ${{ secrets.TOKEN_TELEGRAM }}

      - name: Cleaning reminder
        if: github.event.schedule == '0 16 * * *'
        run: MODE=cleaning python bot.py
        env:
          TOKEN_TELEGRAM: ${{ secrets.TOKEN_TELEGRAM }}

      - name: Cooking reminder
        if: github.event.schedule == '0 18 * * *'
        run: MODE=cooking python bot.py
        env:
          TOKEN_TELEGRAM: ${{ secrets.TOKEN_TELEGRAM }}
